[package]
name = "kvik_aktions_prototype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "0.2.4"
sublime_fuzzy = "0.7.0"

[features]
